---
# tasks file for ansible-nfs-server
- include_tasks: set-facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: config.yml
